### ISSUE TITLE
Align_HMMclean step issue

### ISSUE THREAD

**Issue by UagenZlepe** [chrisjackson-pellicle/Yang-and-Smith-paralogy-resolution#5]
Hi there Chris,
I just pulled the update. I was still using the old container and config from the ASBS workshop last year until today. Now I have run into problems, though. Any thoughts on what is going wrong?

```
executor >  local (5)
[6e/3de5d2] process > CHECK_AND_BATCH_PARALOGS_01 (1) [100%] 1 of 1 ✔
[07/82d916] process > ALIGN_AND_HMMCLEAN_02 (8)       [  6%] 1 of 15, failed: 1
[-        ] process > ALIGNMENT_TO_TREE_03            -
[-        ] process > TRIM_TIPS_04                    -
[-        ] process > MASK_TIPS_05                    -
[-        ] process > CUT_LONG_INTERNAL_BRANCHES_06   -
[-        ] process > WRITE_ALIGNMENT_SUBSET_07       -
[-        ] process > REALIGN_AND_IQTREE_08           -
[-        ] process > PRUNE_PARALOGS_MO_09            -
[-        ] process > PRUNE_PARALOGS_RT_10            -
[-        ] process > PRUNE_PARALOGS_MI_11            -
[-        ] process > WRITE_ALIGNMENT_SUBSET_MO_12    -
[-        ] process > WRITE_ALIGNMENT_SUBSET_RT_13    -
[-        ] process > WRITE_ALIGNMENT_SUBSET_MI_14    -
[-        ] process > STRIP_NAMES_AND_REALIGN_MO_15   -
[-        ] process > STRIP_NAMES_AND_REALIGN_RT_16   -
[-        ] process > STRIP_NAMES_AND_REALIGN_MI_17   -
Error executing process > 'ALIGN_AND_HMMCLEAN_02 (3)'

Caused by:
  Missing output file(s) `batch_*_alignments_hmmcleaned` expected by process `ALIGN_AND_HMMCLEAN_02 (3)`

Command executed:

  python /Yang-and-Smith-RBGV-scripts/02a_align_and_hmmclean.py     batch_12     -no_supercontigs               -pool 1     -threads 1

Command exit status:
  0

```

here is my .config file options:

nextflow.enable.dsl=2

```
// set some defaults for pipeline parameters
params {
	help = false
    outdir = 'results'
    internal_outgroups = false
    external_outgroups_file = false
    external_outgroups = false
    pool = 1
    threads = 1
    process_04_trim_tips_relative_cutoff = 0.2
    process_04_trim_tips_absolute_cutoff = 0.4
    process_06_branch_length_cutoff = 0.3
    process_06_minimum_taxa = 20
    process_09_prune_paralog_MO_minimum_taxa = 2
    process_10_prune_paralogs_RT_minimum_ingroup_taxa = 2
    process_11_prune_paralogs_MI_relative_tip_cutoff = 0.2
    process_11_prune_paralogs_MI_absolute_tip_cutoff = 0.4
    process_11_prune_paralogs_MI_minimum_taxa = 2
    no_supercontigs = true
    bootstraps = true
    batch_size = 20
    use_muscle = false
    mafft_algorithm = false
    use_fasttree = false
}
```

Thanks Chris, let me know if there is more information I could provide.

**Comment by chrisjackson-pellicle** [comment]
Hi Duncan,

This one's my fault - it's the same issue I replied to in the Discussions tab:

> This was my fault - when I last made changes (quite a few months ago now) I forgot to update the tag on the Singularity container, so pulling the :latest was actually pulling an old version...
> 
> Should be fixed now, but you'll need to download the Singularity container again. Let me know how you go!

So, re-downloading the Singularity container should do the trick. Sorry for the hassle, and let me know if there are any issues!

Cheers,

Chris

**Comment by UagenZlepe** [comment]
Hi Chris,
This morning I re-pulled the container and edited the config to reference it.

then tried running the Y&S pipeline:
```
nextflow run ~/353Workshop/Yang-and-Smith-paralogy-resolution/yang-and-smith-rbgv-pipeline.nf -c ~/353Workshop/Yang-and-Smith-paralogy-resolution/yang-and-smith-rbgv.config --internal_outgroups 7287-25-0-1_S26_L001,7287-29-0-1_S30_L001 --hybpiper_paralogs_directory ~/353Workshop/HybPiper-rbgv/results/11_paralogs
```
but still got an error:

```
executor >  local (5)
[eb/ed1e05] process > CHECK_AND_BATCH_PARALOGS_01 (1) [100%] 1 of 1 ✔
[7f/4aca00] process > ALIGN_AND_HMMCLEAN_02 (3)       [  0%] 0 of 18
[-        ] process > ALIGNMENT_TO_TREE_03            -
[-        ] process > TRIM_TIPS_04                    -
[-        ] process > MASK_TIPS_05                    -
[-        ] process > CUT_LONG_INTERNAL_BRANCHES_06   -
[-        ] process > WRITE_ALIGNMENT_SUBSET_07       -
[-        ] process > REALIGN_AND_IQTREE_08           -
[-        ] process > PRUNE_PARALOGS_MO_09            -
[-        ] process > PRUNE_PARALOGS_RT_10            -
[-        ] process > PRUNE_PARALOGS_MI_11            -
[-        ] process > WRITE_ALIGNMENT_SUBSET_MO_12    -
[-        ] process > WRITE_ALIGNMENT_SUBSET_RT_13    -
[-        ] process > WRITE_ALIGNMENT_SUBSET_MI_14    -
[-        ] process > STRIP_NAMES_AND_REALIGN_MO_15   -
[-        ] process > STRIP_NAMES_AND_REALIGN_RT_16   -
[-        ] process > STRIP_NAMES_AND_REALIGN_MI_17   -








executor >  local (5)
[eb/ed1e05] process > CHECK_AND_BATCH_PARALOGS_01 (1) [100%] 1 of 1 ✔
[7f/4aca00] process > ALIGN_AND_HMMCLEAN_02 (3)       [  6%] 1 of 15, failed: 1
[-        ] process > ALIGNMENT_TO_TREE_03            -
[-        ] process > TRIM_TIPS_04                    -
[-        ] process > MASK_TIPS_05                    -
[-        ] process > CUT_LONG_INTERNAL_BRANCHES_06   -
[-        ] process > WRITE_ALIGNMENT_SUBSET_07       -
[-        ] process > REALIGN_AND_IQTREE_08           -
[-        ] process > PRUNE_PARALOGS_MO_09            -
[-        ] process > PRUNE_PARALOGS_RT_10            -
[-        ] process > PRUNE_PARALOGS_MI_11            -
[-        ] process > WRITE_ALIGNMENT_SUBSET_MO_12    -
[-        ] process > WRITE_ALIGNMENT_SUBSET_RT_13    -
[-        ] process > WRITE_ALIGNMENT_SUBSET_MI_14    -
[-        ] process > STRIP_NAMES_AND_REALIGN_MO_15   -
[-        ] process > STRIP_NAMES_AND_REALIGN_RT_16   -
[-        ] process > STRIP_NAMES_AND_REALIGN_MI_17   -
Error executing process > 'ALIGN_AND_HMMCLEAN_02 (7)'

Caused by:
  Missing output file(s) `batch_*_alignments_hmmcleaned` expected by process `ALIGN_AND_HMMCLEAN_02 (7)`

Command executed:

  python /Yang-and-Smith-RBGV-scripts/02a_align_and_hmmclean.py     batch_15     -no_supercontigs               -pool 1     -threads 1

Command exit status:
  0

Command output:
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/4691.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5131.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5163.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5296.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5449.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5634.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5660.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5816.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5865.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5899.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5944.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/5945.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/6404.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/6531.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/6533.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/6620.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/6785.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/6946.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/7241.paralogs.fasta
  Performing MAFFT alignment with command" mafft --auto --thread 1 --adjustdirection batch_15/7628.paralogs.fasta
  
  20 alignments generated from 20 fasta files...

Work dir:
  ~/353Workshop/yang_and_smith_analysis/work/87/a93f17464af6f5da0209838ce04e77

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

Any ideas? Hope it isn't a manjaro thing again ... although the container from the workshop was working fine so not sure.
Cheers,
Duncan

**Comment by chrisjackson-pellicle** [comment]
Ah, there's a bug when using the `--no_supercontigs` flag. I see that you didn't supply this at the command line, and that instead your `*.config` file contains `no_supercontigs = true` and `bootstraps = true`. Did you change these values yourself? The config file on this repo was last updated November 2021, and has `false` for both these parameters.

If you didn't mean to use `no_supercontigs = true` you can just adjust the `*.config` file and the pipeline should work fine as is. I'll work on a fix for `no_supercontigs = true` now...

**Comment by UagenZlepe** [comment]
That will be it. Yes, I used the `nosupercontigs = true` in the hybpiper .config so thought to also do the same with this one, too. Seems to be running now that I changed it back. Thanks Chris.

**Comment by chrisjackson-pellicle** [comment]
Oh, if you've run `HybPiper-RGBV` with the `--no_supercontigs` flag, it is a good idea to run Yang-and-Smith with it too. I've just pushed new a hacky-but-functional version of `yang-and-smith-rbgv-pipeline.nf` wich should now work correctly with `--no_supercontigs`.

**Comment by UagenZlepe** [comment]
Yep, perfect, not getting the errors with `no_supercontigs` anymore. Thanks, Chris.

**Comment by UagenZlepe** [comment]
Hi Chris, it was running well until process 08 before giving another error:

```
executor >  local (45)
[0b/b77a43] process > CHECK_AND_BATCH_PARALOGS_01 (1) [100%] 1 of 1 ✔
[4d/b930d0] process > ALIGN_AND_HMMCLEAN_02 (13)      [100%] 18 of 18 ✔
[68/40cfc1] process > ALIGNMENT_TO_TREE_03 (18)       [100%] 18 of 18 ✔
[3e/8585fc] process > TRIM_TIPS_04                    [100%] 1 of 1 ✔
[8d/e27800] process > MASK_TIPS_05                    [100%] 1 of 1 ✔
[fb/116375] process > CUT_LONG_INTERNAL_BRANCHES_06   [100%] 1 of 1 ✔
[af/7c1c07] process > WRITE_ALIGNMENT_SUBSET_07       [100%] 1 of 1 ✔
[29/b453bd] process > REALIGN_AND_IQTREE_08 (1)       [  6%] 1 of 15, failed: 1
[-        ] process > PRUNE_PARALOGS_MO_09            -
[-        ] process > PRUNE_PARALOGS_RT_10            -
[-        ] process > PRUNE_PARALOGS_MI_11            -
[-        ] process > WRITE_ALIGNMENT_SUBSET_MO_12    -
[-        ] process > WRITE_ALIGNMENT_SUBSET_RT_13    -
[-        ] process > WRITE_ALIGNMENT_SUBSET_MI_14    -
[-        ] process > STRIP_NAMES_AND_REALIGN_MO_15   -
[-        ] process > STRIP_NAMES_AND_REALIGN_RT_16   -
[-        ] process > STRIP_NAMES_AND_REALIGN_MI_17   -
Error executing process > 'REALIGN_AND_IQTREE_08 (6)'

Caused by:
  Process `REALIGN_AND_IQTREE_08 (6)` terminated with an error exit status (1)

Command executed:

  python /Yang-and-Smith-RBGV-scripts/08a_alignment_and_tree.py     all_hmmclean_alignments_combined     batch_14               -internal_outgroup 7287-25-0-1_S26_L001 -internal_outgroup 7287-29-0-1_S30_L001      -no_supercontigs                    -threads_pool 1     -threads_mafft 1
  
  batch_trees=(batch_*_outgroups_added_alignments_clustal_tree_files)
  batch_trees_rename=${batch_trees/clustal_/}
  mv $batch_trees $batch_trees_rename
  
  
  batch_aln=(batch_*_outgroups_added_alignments)
  batch_aln_clustal=(batch_*_outgroups_added_alignments_clustal)
  rm -r $batch_aln
  mv $batch_aln_clustal $batch_aln

Command error:
  Traceback (most recent call last):
    File "/Yang-and-Smith-RBGV-scripts/08a_alignment_and_tree.py", line 654, in <module>
      sys.exit(main())
    File "/Yang-and-Smith-RBGV-scripts/08a_alignment_and_tree.py", line 643, in main
      iqtree_threads=results.threads_iqtree,
  AttributeError: 'Namespace' object has no attribute 'threads_iqtree'
```

**Comment by chrisjackson-pellicle** [comment]
Ugh, yep, another bug, but one that'll need a new Singularity container. Sorry Duncan - I clearly didn't test the `--no_supercontigs` flag properly. It works fine when using FastTreeMP (flag `--use_fasttree`) instead of IQ-TREE, but I'll build and upload a new container first thing Monday

**Comment by chrisjackson-pellicle** [comment]
Sorry for the delay - I've uploaded a new container that works with the `--no_supercontigs` flag in my tests, using the tag `:test` i.e. `hybpiper-yang-and-smith-rbgv:test`. Are you able to pull this container and confirm that it works before I make it the default container?

**Comment by UagenZlepe** [comment]
All good! 
This was with all the default options apart from `--no_supercontigs = true`

```
[bb/b471d2] process > CHECK_AND_BATCH_PARALOGS_01 (1)    [100%] 1 of 1 ✔
[cc/c5d95a] process > ALIGN_AND_HMMCLEAN_02 (15)         [100%] 18 of 18 ✔
[d1/e19ce3] process > ALIGNMENT_TO_TREE_03 (18)          [100%] 18 of 18 ✔
[8d/62a5ae] process > TRIM_TIPS_04                       [100%] 1 of 1 ✔
[ea/309cac] process > MASK_TIPS_05                       [100%] 1 of 1 ✔
[0b/b2f9f0] process > CUT_LONG_INTERNAL_BRANCHES_06      [100%] 1 of 1 ✔
[f8/e3f3c4] process > WRITE_ALIGNMENT_SUBSET_07          [100%] 1 of 1 ✔
[30/205eec] process > REALIGN_AND_IQTREE_08 (16)         [100%] 20 of 20 ✔
[25/c73714] process > PRUNE_PARALOGS_MO_09               [100%] 1 of 1 ✔
[ed/0d2e0e] process > PRUNE_PARALOGS_RT_10               [100%] 1 of 1 ✔
[6c/706990] process > PRUNE_PARALOGS_MI_11               [100%] 1 of 1 ✔
[0c/1a51a2] process > WRITE_ALIGNMENT_SUBSET_MO_12       [100%] 1 of 1 ✔
[64/146cc0] process > WRITE_ALIGNMENT_SUBSET_RT_13       [100%] 1 of 1 ✔
[82/996c7f] process > WRITE_ALIGNMENT_SUBSET_MI_14       [100%] 1 of 1 ✔
[bc/d36a68] process > STRIP_NAMES_AND_REALIGN_MO_15 (5)  [100%] 15 of 15 ✔
[be/e6a24d] process > STRIP_NAMES_AND_REALIGN_RT_16 (77) [100%] 78 of 78 ✔
[e2/54ce24] process > STRIP_NAMES_AND_REALIGN_MI_17 (33) [100%] 35 of 35 ✔
Completed at: 01-Jun-2022 11:54:42
Duration    : 1h 49m 10s
CPU hours   : 10.6
Succeeded   : 195
```
I'll try it out with some different options and see how it goes, too.
